version: '3.8'

networks:
  proxy-swarm:
    external: true
  internal:
    driver: overlay

services:
  frontend:
    image: ${COMPOSE_PROJECT_NAME}_frontend
    volumes:
      - frontend_build:/app/build
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: ${COMPOSE_PROJECT_NAME}_backend
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - internal
      - proxy-swarm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}-backend.loadbalancer.server.port=8000"
        - "traefik.docker.network=proxy-swarm"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./nginx/custom.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
      - proxy-swarm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}-frontend.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy-swarm"

volumes:
  mongo_data:
  frontend_build: