http:
  middlewares:
    websocket:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
      retry:
        attempts: 3
        initialInterval: "500ms"
      forwardAuth:
        address: "http://backend:8000/api/status"
        trustForwardHeader: true
  
  routers:
    websocket:
      entryPoints:
        - "websecure"
      rule: "Host(`nexiosdigital.com`) && PathPrefix(`/ws`)"
      service: "backend@docker"
      tls: {}
      middlewares:
        - "websocket"

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
        passHostHeader: true
